# Generated by Django 4.2.11 on 2024-04-02 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import honor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nameOfOffender', models.CharField(max_length=200)),
                ('className', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('addInfo', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'NEW'), (2, 'IN_PROGRESS'), (3, 'RESOLVED')], default=honor.models.ResolutionStatus['NEW'])),
                ('admin_comments', models.TextField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honor.report')),
            ],
        ),
    ]
