# Generated by Django 4.2.11 on 2024-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
