# Generated by Django 4.2.11 on 2024-04-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0002_alter_report_admin_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='session_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
