# Generated by Django 4.2.10 on 2024-04-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0003_report_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report_files/'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
