# Generated by Django 4.2.11 on 2024-04-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0005_alter_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
